In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import os

In [4]:
from datetime import datetime

In [5]:
df = pd.read_excel(r".\FSIS-Recall-Summary-2014.xlsx", header=1, index =2)

In [6]:
df.head(5)

,Recall Date,Recall Number,Recall Class,Product,Reason for Recall,Pounds Recalled
0,2014-01-10,001-2014,I,Mechanically Separated Chicken Products,Salmonella,33840
1,2014-01-13,002-2014,I,Various Beef Products,Other,42103
2,2014-01-15,003-2014,I,Beef Franks,Undeclared Allergen,2664
3,2014-01-17,004-2014,II,Beef and Pork Products,Undeclared Allergen,130000
4,2014-01-17,005-2014,I,Spiral Hams,Listeria monocytogenes,67113

In [27]:
pd.DataFrame(df)

,Recall Date,Recall Number,Recall Class,Product,Reason for Recall,Pounds Recalled
0,2014-01-10,001-2014,I,Mechanically Separated Chicken Products,Salmonella,33840
1,2014-01-13,002-2014,I,Various Beef Products,Other,42103
2,2014-01-15,003-2014,I,Beef Franks,Undeclared Allergen,2664
3,2014-01-17,004-2014,II,Beef and Pork Products,Undeclared Allergen,130000
4,2014-01-17,005-2014,I,Spiral Hams,Listeria monocytogenes,67113
...,...,...,...,...,...,...
89,2014-12-27,090-2014,I,Pork products,Undeclared Allergen,83666
90,2014-12-27,091-2014,I,Chicken and Beef Products,Undeclared Allergen,55813
91,2014-12-29,092-2014,I,Beef and Pork Products,Undeclared Allergen,38400
92,2014-12-31,093-2014,I,Chicken Products,Undeclared Allergen,5300
93,2014-12-31,094-2014,I,Canned Soup Products,Undeclared Allergen,4474

In [11]:
df.count()

Recall Date          94
Recall Number        94
Recall Class         94
Product              94
Reason for Recall    94
Pounds Recalled      94
dtype: int64

In [9]:
dupes=df[df.duplicated(('Reason for Recall', 'Product'), keep=False)]
dupes.sort_values(['Product'])

,Recall Date,Recall Number,Recall Class,Product,Reason for Recall,Pounds Recalled
57,2014-09-12,058-2014,I,Beef Jerky Products,Other,0
64,2014-10-03,065-2014,I,Beef Jerky Products,Other,48
61,2014-09-27,062-2014,I,Beef Jerky Products,Other,8
3,2014-01-17,004-2014,II,Beef and Pork Products,Undeclared Allergen,130000
91,2014-12-29,092-2014,I,Beef and Pork Products,Undeclared Allergen,38400
72,2014-10-24,073-2014,I,Chicken Products,Salmonella,28980
69,2014-10-16,070-2014,II,Chicken Products,Undeclared Allergen,115505
43,2014-07-03,044-2014,I,Chicken Products,Salmonella,0
92,2014-12-31,093-2014,I,Chicken Products,Undeclared Allergen,5300
18,2014-04-01,019-2014,I,Chicken Products,Undeclared Allergen,8730
17,2014-03-07,018-2014,I,Chicken Products,Undeclared Allergen,29200
52,2014-08-15,053-2014,I,Ground Beef Products,E. coli O157:H7,368
29,2014-05-19,030-2014,I,Ground Beef Products,E. coli O157:H7,1800000
81,2014-11-22,082-2014,I,Ground Beef Products,E. coli O157:H7,1200
28,2014-05-16,029-2014,III,Pork Products,Other,449000
75,2014-11-06,076-2014,I,Pork Products,Undeclared Allergen,6560
79,2014-11-19,080-2014,II,Pork Products,Undeclared Allergen,2902
86,2014-12-22,087-2014,I,Pork Products,Other,26108
88,2014-12-27,089-2014,I,Pork Products,Undeclared Allergen,190450
46,2014-07-22,047-2014,II,Sausage Product,Undeclared Allergen,82440
49,2014-08-06,050-2014,I,Sausage Product,Undeclared Allergen,106800
80,2014-11-19,081-2014,I,Sausage Products,Undeclared Allergen,14
38,2014-06-25,039-2014,II,Sausage Products,Undeclared Allergen,1761
12,2014-02-08,013-2014,I,Various Beef Products,Other,8742700
1,2014-01-13,002-2014,I,Various Beef Products,Other,42103

In [22]:
df[df.Product.str.startswith('P')]
# can replace finding with new thing df.Product=df.Product.str.replace('Pork', 'Pig')
# verify change len(df[df.Product.str.startswith('Pork')])

,Recall Date,Recall Number,Recall Class,Product,Reason for Recall,Pounds Recalled
27,2014-05-16,028-2014,I,Pork and Poultry Products,Other,222000
28,2014-05-16,029-2014,III,Pork Products,Other,449000
37,2014-06-21,038-2014,I,Pork Mini Buns Products,Undeclared Allergen,332
39,2014-06-25,040-2014,III,Pork Products,Undeclared Substance,34
56,2014-09-12,057-2014,I,Pork Sausage,Undeclared Allergen,4820
63,2014-10-02,064-2014,I,Pork Blood Product,Other,160
75,2014-11-06,076-2014,I,Pork Products,Undeclared Allergen,6560
77,2014-11-14,078-2014,I,Pierogi Products,Undeclared Allergen,2059
78,2014-11-15,079-2014,I,Pretzel Dog Products,Undeclared Allergen,1208951
79,2014-11-19,080-2014,II,Pork Products,Undeclared Allergen,2902
82,2014-12-04,083-2014,I,Pork Belly Product,Other,44372
86,2014-12-22,087-2014,I,Pork Products,Other,26108
88,2014-12-27,089-2014,I,Pork Products,Undeclared Allergen,190450
89,2014-12-27,090-2014,I,Pork products,Undeclared Allergen,83666

In [26]:
group_by_product = df.groupby('Product')
group_by_product.sum()

                                   Pounds Recalled
Product
 Uncured Beef Corn Dogs                        607
Baby Back Ribs                                  36
Barbecue Pork Products                         350
Beef Franks                                   2664
Beef Jerky                                     365
...                                            ...
Turkey Base                                   3156
Various Beef Products                      8784803
Various Chicken Products                        59
Various Meat Products                         8895
Various Meat and Poultry Products           144000

[69 rows x 1 columns]